apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.secrets.DB_USERNAME }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
