services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: python app.py
    ports:
      - "5000:5000"

  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: flake8 .

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: pytest

  format:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: black .
