services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  flask:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "python setup_db.py && gunicorn -w 4 -b 0.0.0.0:5000 app:app"
volumes:
  dbdata:

